// Note that this is only used when the dev python server is
// available. When using nginx, this is generated by nginx itself
// See nginx.conf
window.backendHttpsUrl = 'https://staging-nginz-https.zinfra.io';
