// Note that this is only used when the dev python server is
// available. When using nginx, this is generated by nginx itself
// See nginx.conf
// TODO: Alternatively, we could have the same login on the python server
// but I think this works well enough and not sure python is actually
// needed given this docker build. Perhaps we can remove it?
window.backendHttpsUrl = 'https://staging-nginz-https.zinfra.io';
